=== 4850rgcl/4850lab7/data/timetable.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT timetable (days, timeslots, courses)>

<!ELEMENT days (day)>
<!ELEMENT timeslots (#PCDATA)>
<!ELEMENT courses (#PCDATA)>

<!ELEMENT day (timeslot)>
<!ELEMENT timeslot (course)>
<!ELEMENT course (booking)>
<!ELEMENT booking (#PCDATA)>


<!ATTLIST day weekday (mon|tues|weds|thurs|fri) #REQUIRED>
<!ATTLIST timeslot start-time CDATA #REQUIRED end-time CDATA #REQUIRED>
<!ATTLIST course program CDATA #REQUIRED code CDATA #REQUIRED>
<!ATTLIST booking instructor CDATA #REQUIRED>

=== 4850rgcl/4850lab7/data/timetable.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE timetable SYSTEM "timetable.dtd">
<timetable>
    <days>
        <day weekday="mon">
            <timeslot start-time="0830" end-time="0920">
                <course program="ACIT" code="4950">
                    <booking instructor="Jim">
                        Sauna
                    </booking>
                </course>
            </timeslot>
        </day>
    </days>
    <timeslots>TIME</timeslots>
    <courses>COURSES</courses>
</timetable>
